image: vauxoo/odoo-80-image-shippable-auto
stages:
  - test
  - build
  - upload_image

variables:
    PSQL_VERSION: "9.5"
    VERSION: "11.0"
    ODOO_REPO: "vauxoo/odoo"
    ODOO_BRANCH: "11.0"
    CUSTOMER: "vauxoo"
    BASE_IMAGE: "vauxoo/odoo-110-image"

lint:
  stage: test
  tags:
    - lint
  variables:
    LINT_CHECK: "1"
    TESTS: "0"
  script:
    - export TRAVIS_BUILD_DIR=$(pwd)
    - sudo apt-get update && sudo apt-get install -y dos2unix
    - pip install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools check_keys
    - git clone https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - travis_install_nightly
    - travis_run_tests

test:
  stage: test
  tags:
    - odoo
    - test
  variables:
    LINT_CHECK: "0"
    TESTS: "1"
  script:
    - pip3 install requests_mock
    - export TRAVIS_BUILD_DIR=$(pwd)
    - apt-get update && apt-get install -y tree dos2unix
    - pip install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools check_keys
    - source /.repo_requirements/virtualenv/python3.5/bin/activate
    - git clone https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - travis_install_nightly
    - travis_run_tests
    - travis_after_tests_success || true
    - coverage html --rcfile=${TRAVIS_BUILD_DIR}/.coveragerc -d $CI_COMMIT_REF_NAME
    - coverage report -m --show-missing --rcfile=${TRAVIS_BUILD_DIR}/.coveragerc | tee $CI_COMMIT_REF_NAME/coverage.txt
  artifacts:
    paths:
      - $CI_COMMIT_REF_NAME

nodemo:
  stage: test
  tags:
    - odoo
    - test
  variables:
    LINT_CHECK: "0"
    TESTS: "1"
    TEST_ENABLE: "0"
    OPTIONS: "--without-demo=all"
    INSTALL_OPTIONS: "--without-demo=all"
  script:
    - pip3 install requests_mock
    - export TRAVIS_BUILD_DIR=$(pwd)
    - apt-get update && apt-get install -y tree dos2unix
    - pip install deployv-addon-gitlab-tools
    - deployvcmd gitlab_tools check_keys
    - source /.repo_requirements/virtualenv/python3.5/bin/activate
    - git clone https://github.com/vauxoo/maintainer-quality-tools.git -b master ${HOME}/maintainer-quality-tools
    - export PATH=${HOME}/maintainer-quality-tools/travis:${HOME}/gitlab_tools:${PATH}
    - travis_install_nightly
    - travis_run_tests
    - travis_after_tests_success || true

build:
  stage: build
  tags:
    - build
  variables:
    INSTALL: "account_xunnel"
    CUSTOMER: "account_xunnel"
  script:
    - deployvcmd gitlab_tools test_images --psql_image='vauxoo/docker-postgresql:9.6-ci' --push_image

bump:
  stage: upload_image
  only:
      - 11.0@vauxoo/xunnel-account
  when: on_success
  tags:
    - odoo
    - test
  script:
    - |
      case "$CI_COMMIT_MESSAGE" in
        *Bump*)
          ;;
        *)
          git config --global user.email "coward@vauxoo.com"
          git config --global user.name "Coward - Auto release"
          pip install -U bumpversion
          git clone -b 11.0 --single-branch git@git.vauxoo.com:vauxoo/xunnel-account.git
          cd xunnel-account
          bumpversion patch
          git push origin 11.0
          ;;
        esac

